modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="${issues_url}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="${mod_url}"
    iconFile="assets/thecopperierage/icon.png"
    authors="Lunade/AViewFromTheTop, Lufurrius"
    description='''
Expends and enhances the theme of The Copper Age drop. New blocks and mechanics, many tweaks, and awesome optional retextures!
    '''

[[mixins]]
config="thecopperierage.mixins.json"

[[ dependencies.thecopperierage ]]
    modId="neoforge"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.thecopperierage ]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.thecopperierage ]]
    modId="frozenlib"
    type="required"
    versionRange="[${frozenlib_version},)"
    ordering="NONE"
    side="BOTH"

[[ dependencies.thecopperierage ]]
    modId="cloth-config"
    type="optional"
    versionRange="*"
    ordering="NONE"
    side="BOTH"
